server:
  port: 80
spring:
  application:
    name: cloud-order-service

eureka:

  client:
    #表示将自己注册人EurekaServer
    register-with-eureka: false
    # 是否从EurekaServer抓取已有的注册信息 ,默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka

#开启属性
feign:
  hystrix:
    enabled: true